
# Syntax highlighting
markdown: 			 redcarpet
highlighter: 		 pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
name:				         A Never-ending Dream
title:               A Never-ending Dream
tagline:             'learning how to build a lasting company'
description:         'learning how to build a lasting company'
url:                 http://www.aneverendingdream.com
baseurl:             '/'

author:
  name:           	 'Vincent Chan'
  url:            	 https://twitter.com/vincentchan

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
